### ISSUE TITLE
File uploads are failing with not-so-clean messages

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-simcore-clients#150]
When hitting the api server pretty hard (now really 100 parallel jobs asking for file uploads), I'm getting the following error. Maybe it's not surprising that this happens given the load. But maybe the errors messages can be better?
This is on aws master

![Screenshot 2024-04-24 at 15 39 22](https://github.com/ITISFoundation/osparc-simcore-clients/assets/3098670/83927345-3bfb-40fa-a58f-f1883c540d61)

![Screenshot 2024-04-24 at 15 38 48](https://github.com/ITISFoundation/osparc-simcore-clients/assets/3098670/ed64d34f-97ce-4bae-b038-93db48729748)

Code: https://github.com/wvangeit/osparc-pyapi-tests/blob/4730bc351d920fb69127bb94b377f08585d2c859/noninter1/run_study.py#L47

**Comment by wvangeit** [comment]
I put it in this repo, since i think it's mostly an error message issue, but feel free to move

**Comment by bisgaard-itis** [comment]
Closing this as it has been moved [here](https://github.com/ITISFoundation/osparc-simcore-clients/issues/151)
