### ISSUE TITLE
Add test to run jupyter notebooks

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore-clients#36]
Jupyter notebooks are currently auto-generated from markdown doc. Verify that every code cell runs "as is" (e.g. no variables missing, etc). Ideally this should be an automatic job in the CI

**Comment by bisgaard-itis** [comment]
The two PRs listed above accomplished this task. These jobs currently run on the [e2e-portal-testing](https://git.speag.com/oSparc/e2e-portal-testing) repo on the `master` branch
