### ISSUE TITLE
python client wrapper based on generator

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore-clients#38]
When API exposes job pagination, I would like to have a compatible client function ``JobsAPI.list_jobs`` that includes pagination parameters (defaulted to compatible values) and an extra function that ``JobsAPi.iter_jobs`` to seamlessly iterate all jobs as with https://github.com/ITISFoundation/osparc-simcore/blob/master/packages/pytest-simcore/src/pytest_simcore/helpers/utils_docker_registry.py#LL48C5-L66C74

**Comment by bisgaard-itis** [comment]
@pcrespov I consider this issue done, but I leave it open in case you have further remarks/thought on what needs to happen. Please let me know
