### ISSUE TITLE
Expose osparc python package within the sparc.client

### ISSUE THREAD

**Issue by bisgaard-itis** [ITISFoundation/osparc-simcore-clients#48]
Here's a list of tasks which should be achieved:

```[tasklist]
- [ ] https://github.com/nih-sparc/sparc.client/pull/17
- [ ] https://github.com/ITISFoundation/osparc-simcore-clients/issues/60
- [ ] https://github.com/ITISFoundation/osparc-simcore-clients/issues/53
```

**Comment by elisabettai** [comment]
@pcrespov, do you know if the first task in the list is actually this opened PR in sparc.client? https://github.com/nih-sparc/sparc.client/pull/17

**Comment by pcrespov** [comment]
> 
@elisabettai the basic integration is finally merged (2 days ago) and the extension needed e.g. for the tutorials, is still waiting for review in https://github.com/nih-sparc/sparc.client/pull/17. I reminded reviewers today as well.

**Comment by bisgaard-itis** [comment]
@elisabettai concerning https://github.com/ITISFoundation/osparc-simcore-clients/issues/48#issuecomment-1649595661:
I have deleted the first point as the 3rd (now 2nd) is the PR which (once merged) covers the first point.

**Comment by bisgaard-itis** [comment]
Closing this one as all tasks have been achieved. I added another ticket for demonstrating the cross functionalities of the different cores in the sparc.client: https://github.com/ITISFoundation/osparc-simcore-clients/issues/71
