### ISSUE TITLE
Write basic tutorial in "sparc.client-language" in the [tutorial](https://github.com/nih-sparc/sparc.client/blob/main/docs/tutorial.ipynb)

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore-clients#60]
This was pointed out at the Tech call (July 13) by @mguidon.

1. The current plan is to have the documentation on [Readme](https://dash.readme.com/project/sparc/v1.0/docs/sparc-python-client). We can get help in moving/copying our documentation there. See this wrike ticket here (https://www.wrike.com/open.htm?id=920664113)

2. They asked for ideas of a cross-core tutorial (https://docs.google.com/spreadsheets/d/1WZIjBVo2wyQyxiPP7KzEmchBf_9UX48hvaielX1kST4/edit#gid=944422487) until Wednesday, July 19th such that it can be discussed in the PI meeting

This task is about Point 1.
fyi @pcrespov 

```[tasklist]
- [ ] https://github.com/nih-sparc/sparc.client/pull/21
- [x] add above tutorial to Readme in Markdown format
```

**Comment by bisgaard-itis** [comment]
I recently completed the last task on the list. Hence closing this issue
