### ISSUE TITLE
Broken link in the readme page

### ISSUE THREAD

**Issue by lmoyasans** [ITISFoundation/osparc-simcore-clients#76]
In the readme section, when trying to open the "Basic tutorial option", it loads the following link:

https://itisfoundation.github.io/osparc-simcore-clients/#/clients/python/artifacts/docs/BasicTutorial

The webpage states an error message of 404 so the web is not being correctly load/generated.

**Comment by wvangeit** [comment]
The tutorial is atm available at: https://itisfoundation.github.io/osparc-simcore-clients/#/clients/python/artifacts/docs/BasicTutorial_v0.6.0.md

@pcrespov Maybe temporarily I can hardcode that in the readme? Or do you want that to be dynamically generated?

**Comment by pcrespov** [comment]
> The tutorial is atm available at: https://itisfoundation.github.io/osparc-simcore-clients/#/clients/python/artifacts/docs/BasicTutorial_v0.6.0.md
> 
> @pcrespov Maybe temporarily I can hardcode that in the readme? Or do you want that to be dynamically generated?

@wvangeit please check with @bisgaard-itis . It would be good that this is ready for the release planned for Monday. thx

**Comment by bisgaard-itis** [comment]
@wvangeit I think it would  make sense to just delete it and then state that tutorials can now be found in the documentation. The thing is that we started versioning the tutorials, so I wouldn't know which specific one to point to here. I.e. I would change it to 
```
To get started using the tools developed in this repository, take a look at the [documentation](https://itisfoundation.github.io/osparc-simcore-clients) (which also holds tutorials)
```
What do you think?

**Comment by bisgaard-itis** [comment]
This was resolved by @wvangeit's merge above
